### ISSUE TITLE
`requireJsDomEnv := true` does not work on ScalaJS 1.0.0

### ISSUE THREAD

**Issue by raquo** [scalacenter/scalajs-bundler#332]
plugins.sbt:
```
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.0.0")
addSbtPlugin("ch.epfl.scala" % "sbt-scalajs-bundler" % "0.17.0")
```

build.sbt:
```
enablePlugins(ScalaJSBundlerPlugin)
version in installJsdom := "16.2.0"
requireJsDomEnv in Test := true
```

`sbt test` result:
```
TypeError: jsdom.createVirtualConsole is not a function
    at /Users/raquo/code/scala/domtestutils/target/scalajs-bundler-jsdom/codeWithJSDOMContext.js:10:30
    at Object.<anonymous> (/Users/raquo/code/scala/domtestutils/target/scalajs-bundler-jsdom/codeWithJSDOMContext.js:37:3)
```

This was addressed in #265, but only for ScalaJS 0.6.x.

Compare [v0.6](https://github.com/scalacenter/scalajs-bundler/blob/3b5d08142be4705f983d066d17872978241becec/sbt-scalajs-bundler/src/main/scala-sjs-0.6/scalajsbundler/JSDOMNodeJSEnv.scala) vs [v1.x](https://github.com/scalacenter/scalajs-bundler/blob/3b5d08142be4705f983d066d17872978241becec/sbt-scalajs-bundler/src/main/scala-sjs-1.x/scalajsbundler/JSDOMNodeJSEnv.scala) versions of JSDOMNodeJSEnv.scala (search for `createVirtualConsole`)

The 1.x version has outdated code that deals with jsdom versions, causing this error.

**Comment by raquo** [comment]
Looks like this fix needs to be ported into scalajs-bundler's copy of JSDOMNodeJSEnv: https://github.com/scala-js/scala-js-env-jsdom-nodejs/commit/2a4efbcec725a9657a9a68dc662fa35e7fa5cd9f

**Comment by julienrf** [comment]
Thanks @raquo for the investigation! Would you have time to issue a PR?

**Comment by sjrd** [comment]
Until a new release is published, the following workaround, though verbose, may be used:

1. Copy the fixed file https://github.com/scalacenter/scalajs-bundler/blob/51771e1f0a91355fc1644063972188937e2688f2/sbt-scalajs-bundler/src/main/scala-sjs-1.x/scalajsbundler/JSDOMNodeJSEnv.scala in your `project/` directory, and change the `package` clause to something else, e.g., `package build`
2. Add the following setting in the `settings` of your Scala.js projects in your `build.sbt`:

       Test / jsEnv := new build.JSDOMNodeJSEnv(build.JSDOMNodeJSEnv.Config((Test / installJsdom).value))

(not tested, but I believe it should work)
