### PR TITLE
Fix usage of jsdom virtualConsole in ScalaJS 1.x (Fixes #332)

### LINKED ISSUE #332: `requireJsDomEnv := true` does not work on ScalaJS 1.0.0
plugins.sbt:
```
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.0.0")
addSbtPlugin("ch.epfl.scala" % "sbt-scalajs-bundler" % "0.17.0")
```

build.sbt:
```
enablePlugins(ScalaJSBundlerPlugin)
version in installJsdom := "16.2.0"
requireJsDomEnv in Test := true
```

`sbt test` result:
```
TypeError: jsdom.createVirtualConsole is not a function
    at /Users/raquo/code/scala/domtestutils/target/scalajs-bundler-jsdom/codeWithJSDOMContext.js:10:30
    at Object.<anonymous> (/Users/raquo/code/scala/domtestutils/target/scalajs-bundler-jsdom/codeWithJSDOMContext.js:37:3)
```

This was addressed in #265, but only for ScalaJS 0.6.x.

Compare [v0.6](https://github.com/scalacenter/scalajs-bundler/blob/3b5d08142be4705f983d066d17872978241becec/sbt-scalajs-bundler/src/main/scala-sjs-0.6/scalajsbundler/JSDOMNodeJSEnv.scala) vs [v1.x](https://github.com/scalacenter/scalajs-bundler/blob/3b5d08142be4705f983d066d17872978241becec/sbt-scalajs-bundler/src/main/scala-sjs-1.x/scalajsbundler/JSDOMNodeJSEnv.scala) versions of JSDOMNodeJSEnv.scala (search for `createVirtualConsole`)

The 1.x version has outdated code that deals with jsdom versions, causing this error.

### PR DESCRIPTION
**Pull request by raquo**
I'm essentially applying [this diff](https://github.com/scala-js/scala-js-env-jsdom-nodejs/commit/2a4efbcec725a9657a9a68dc662fa35e7fa5cd9f) to scalajs-bundler's version of this file.

I couldn't quickly figure out how to run the scalajs-bundler test suite locally, getting unrelated build errors, so I'll rely on travis build checks to see the tests pass I guess?

I did run this code with `publishLocal`, and it worked where 0.17.0 didn't.

### CODE REVIEW

**Comment by sjrd** [comment]
Perhaps it would be worth adding an sbt test for this change, by enforcing jsdom v16.2.0 in the test?

**Comment by sjrd** [comment]
Thanks @raquo for your time in identifying and fixing this issue :)

**Comment by raquo** [comment]
No problem, cheers! Thanks for your guys' work!
